version: "3"

services:
  bio:
    container_name: eCLIP_ENCODE
    build: .
    image: edge299218/deeptools:v0.0.0
    tty: true
    volumes:
      - ../../:/code
      - $HOME/.Xauthority:/root/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
    command: ["/bin/bash"]


