MATPLOTLIB_CONFIG = {
    "font.size": 20,
    # "font.family": "Times New Roman",
    "mathtext.fontset": "stix",
    "figure.figsize": [16, 8],
    "figure.facecolor": (0, 0, 0, 0),
    "axes.facecolor": (0, 0, 0, 0),
    "savefig.facecolor": (0, 0, 0, 0),
    "figure.subplot.left": 0.11,
    "figure.subplot.right": 0.90,
    "figure.subplot.top": 0.95,
    "figure.subplot.bottom": 0.08,
    "figure.subplot.hspace": 0.1,
    "savefig.format": "pdf",
    "xtick.direction": "in",
    "ytick.direction": "in",
    "xtick.top": True,
    "ytick.right": True,
    "xtick.minor.visible": True,
    "ytick.minor.visible": True,
    "legend.edgecolor": "black",
    "legend.facecolor": "white",
}
